project_id = "nvjjifnzwrueutbirpde"

[functions.allocatePrizes]
verify_jwt = true

[functions.allocateInstitutionPrizes]
verify_jwt = true

[functions.finalize]
verify_jwt = true

[functions.generatePdf]
verify_jwt = true

[functions.pmPing]
verify_jwt = false

[functions.publicTeamPrizes]
verify_jwt = false